import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";

const arialFont = localFont({
  src: [
    {
      path: "../public/assets/fonts/arial_ce.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/arial_ce.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-arial",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${arialFont.variable} antialiased`}>
        <div className="min-h-screen w-full max-w-[390px] mx-auto px-1 overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
